POST http://localhost:3000/register
Content-Type: application/json

{
    "mail": "nuevo@nuevo.com",
    "password": "1234"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "mail": "nuevo@nuevo.com",
    "password": "1234"
}

###

GET http://localhost:3000/dashboard